### ISSUE TITLE
The state of 32-bit FAudio?

### ISSUE THREAD

**Issue by lemonzest79** [Kron4ek/FAudio-Builds#4]
Hiya

I am wondering on the state of the 32bit parts of FAudio? I had installed Victor Vran in Wine Staging 4.10 and had no sound, one solution I found was to install FAudio to enable Xaudio2 something, I tried to winetricks faudio today and noticed it broke, came to your site and then also noticed you had removed all the 32bit builds of the project, Victor Vran is a 32bit only programme.

Any help or news it gratefully received.

**Comment by Kron4ek** [comment]
Hi. For some reason 32-bit FAudio MinGW build doesn't work, i thought it just doesn't work in some games but then i found out that it doesn't work at all. Maybe i compile it wrong, or that's an upstream bug, i can't say for sure.

For 32-bit games that use XAudio i suggest to install xact using winetricks, that should fix sound issues.

Or you can try to use native FAudio (i mean native Linux library - libFAudio.so) if it's available in your distribution's repositories. In that case it's necessary to use vanilla Wine 4.3+, because Wine-Staging disables FAudio support for now.

**Comment by mozo78** [comment]
Or use native version of the game.

**Comment by lemonzest79** [comment]
Tried using winetricks to install xact and still no sound unfortunately.

**Comment by Kron4ek** [comment]
> Tried using winetricks to install xact and still no sound unfortunately

Doesn't work for me too, i also tested native FAudio library and it doesn't fix sound in this game. But the problem is definitely XAudio related as there is a such line in game logs:

    XAudio2Create failed: 800401f0

So the only solution at the moment is to use native version of the game.
