### ISSUE TITLE
Space Engineers constant audio stutters

### ISSUE THREAD

**Issue by Zemogiter** [Kron4ek/FAudio-Builds#6]
So I've been trying to make this game work in Linux and this is the result:
https://www.reddit.com/r/linux_gaming/comments/avhyxj/space_engineers_finally_playable_on_linux/
Removing mods did not solve the problem. 
I've also tried to change the pulse audio config file:
https://youtu.be/UQ-Ml78kiEE?t=73
but I can't tell if it helped anything.
Like in my reddit post I have set msvcr120, all x3daudio dlls and all xaudio dlls to "native,buildin" because without it the audio stutters constantly even in main menu. With those overrides audiio stutters on main menu for a few seconds then returns to normal and the constant audio stutter happens only in game.
Game log:
[SpaceEngineers.log](https://github.com/doitsujin/dxvk/files/3586528/SpaceEngineers.log)
Wine log:
[playonlinux.log](https://github.com/Kron4ek/FAudio-Builds/files/3586560/playonlinux.log)
Running on wine 4.14 faudio 19.09, Ubuntu 19.04 5.0.0.25-generic, i7-7700K and GTX1080 ti

**Comment by Kron4ek** [comment]
You can try to use native FAudio library (libFAudio.so) instead of MinGW (dll) build, maybe that will fix your issue. In case of native library, you don't need to set overrides for x3daudio/xaudio. There is a [PPA](https://launchpad.net/~cybermax-dexter/+archive/ubuntu/sdl2-backport) (not mine) for Ubuntu 18.04/19.04/19.07.

As the developer of FAudio said [here](https://github.com/FNA-XNA/FAudio/issues/101#issuecomment-448343136), MinGW builds gets the least attention, so i suppose they might be more buggy.

MinGW builds are useful when, for example, you use old Wine version (older than 4.3) that doesn't support FAudio natively or if there is no way to install native FAudio. Otherwise it's better you use native FAudio.

**Comment by Zemogiter** [comment]
So what I need to do is to remove the wineprefix and try again but this time using the native FAudio library from that PPA instead of the MinGW build?

**Comment by Kron4ek** [comment]
Yes, that's right. Install native FAudio from PPA and recreate wineprefix, and this time don't set x3daudio/xaudio overrides in winecfg.

Actually you can just remove all xaudio related overrides from winecfg and Wine should use native FAudio after that, but it's more reliable to recreate wineprefix.

**Comment by Zemogiter** [comment]
Thank you. Problem solved.
